---
format: pdf
---

**Short biography**  
Joseph V. Casillas

Joseph is an Associate Professor of Spanish Linguistics in the Spanish and Portuguese Department and Associate Faculty in the Department of Linguistics at Rutgers University, New Brunswick. 
His main interests are in phonetics, laboratory phonology, and second language acquisition. 
A principle aim of his research is to better understand the relationship between language use and sound representation in the multilingual mind, as well as the structure of sound systems in human languages. 
Most of his research is conducted on bilinguals of varying proficiency and linguistic experience. 
Some of his recent projects have centered on native phonetic experience and its influence on L2 speech production, perception and lexical processing. 
He also focuses his time and attention on coding, statistical analysis, data visualization, and reproducible research, as well as training researchers to implement open research practices in the speech sciences, particularly in Bilingualism/Second Language Acquisition research. 
He also enjoys playing music, Casio watches, and anything related to el andalú.
